### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by thorade** [Souradip-sopho/OpenModelica-Arduino#2]
You might want to add a `.gitignore` file to exclude e.g. the `.mos~` files from your repository.
https://help.github.com/articles/ignoring-files/

**Comment by thorade** [comment]
Here is another .gitignore file that might be interesting:
https://github.com/ibpsa/modelica-ibpsa/blob/master/.gitignore

Ignoring files is also nice in combination with the `git clean` command:
https://git-scm.com/docs/git-clean

**Comment by Souradip-sopho** [comment]
I think that the .gitignore file suggested by you is more appropriate for a package in Dymola environment. This package is however OpenModelica-based.I have used a general .gitignore file.If it is really needed to add any more ignore rules, then that can be added later on.
